name: fire_redux_sample
description: redux_sample using Firestore

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  meta: '>=1.1.0 <2.0.0'
  redux: ^3.0.0
  flutter_redux: ^0.5.0
  flutter:
    sdk: flutter
  cloud_firestore: ^0.9.0
  firebase_auth: 0.8.0+1

dev_dependencies:
  test: ^1.3.0
  mockito: ^3.0.0
  flutter_driver:
    sdk: flutter
  flutter_launcher_icons: "^0.6.1"

flutter_icons:
  image_path: "icon/icon.png" 
  android: true
  ios: true


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - assets/
  uses-material-design: true

  fonts:
    - family: Catamaran
      fonts:
        - asset: fonts/Catamaran-Black.ttf
        - asset: fonts/Catamaran-Bold.ttf
        - asset: fonts/Catamaran-ExtraBold.ttf
        - asset: fonts/Catamaran-ExtraLight.ttf
        - asset: fonts/Catamaran-Light.ttf
        - asset: fonts/Catamaran-Medium.ttf
        - asset: fonts/Catamaran-Regular.ttf
        - asset: fonts/Catamaran-SemiBold.ttf
        - asset: fonts/Catamaran-Thin.ttf

